---
- name: "Container / Docker / Initialize"
  ansible.builtin.include_tasks:
    file: "cnt_docker_initialize.yml"

- name: "Container / Docker / Deploy"
  ansible.builtin.include_tasks:
    file: "cnt_docker_deploy.yml"
  when:
    - cnt_docker['deploy'] is defined
    - cnt_docker['deploy']

- name: "Container / Docker / Finalize"
  ansible.builtin.include_tasks:
    file: "cnt_docker_finalize.yml"
...
