---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      vars:
        cnt_kubectl_application: "{{ test_cnt_kubectl_application_brew }}"
      ansible.builtin.include_role:
        public: true
        name: "cnt_kubectl"

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{ cnt_kubectl_base['run'][cnt_kubectl_application['type']]['kubectl'] }}"
      register: file_stat

    - name: "Verify app is installed"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
