---
# Define supported platforms
cnt_kubectl_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

# Group Linux Distributions by family
cnt_kubectl_os_family: >-
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- elif
      ( ansible_distribution == 'MacOSX' )
  -%}
    {{ 'MacOSX' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}

# Multiplatform packages
cnt_kubectl_profiles_common:
  brew:
    latest:
      supported: true
      packages:
        - name: "kubectl"

# Define common paths
cnt_kubectl_base_common:
  access:
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  paths:
    kube: '.kube'
...
