---
- name: "Container / KubeCtl / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in cnt_kubectl_platforms

- name: "Container / KubeCtl / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + cnt_kubectl_os_family + '.yml' }}"

- name: "Container / KubeCtl / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "cnt_kubectl_prerequisite.yml"
  when:
    - cnt_kubectl['resolve_prereq'] is defined
    - cnt_kubectl['resolve_prereq']
...
