---
- name: "Container / Podman / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in cnt_podman_platforms

- name: "Container / Podman / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"

- name: "Container / Podman / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "cnt_podman_prerequisite.yml"
  when:
    - "'resolve_prereq' in cnt_podman"
    - cnt_podman['resolve_prereq']
...
