---
- name: "Container / Podman / Deploy / Package / Provision prerequisites"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ cnt_podman_application_prereqs }}"
    sys_package_profiles: "{{ cnt_podman_profiles['prereqs'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"

- name: "Container / Podman / Deploy / Package / Provision prerequisites (debian10 backports)"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ cnt_podman_application_prereqs_debian10 }}"
    sys_package_profiles: "{{ cnt_podman_profiles['prereqs'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
  when:
    - ansible_distribution + ansible_distribution_major_version == "Debian10"

- name: "Container / Podman / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ cnt_podman_application }}"
    sys_package_profiles: "{{ cnt_podman_profiles['main'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
