---
- name: "Container / Podman / Initialize"
  ansible.builtin.include_tasks:
    file: "cnt_podman_initialize.yml"

- name: "Container / Podman / Deploy"
  ansible.builtin.include_tasks:
    file: "cnt_podman_deploy.yml"
  when:
    - "'deploy' in cnt_podman"
    - cnt_podman['deploy']

- name: "Container / Podman / Finalize"
  ansible.builtin.include_tasks:
    file: "cnt_podman_finalize.yml"
...
