---
# Define platform specific paths
cnt_docker_base:
  paths: "{{ cnt_docker_base_common['paths'] }}"
  etc: "{{ cnt_docker_base_common['etc'] }}"
  files: "{{ cnt_docker_base_common['files'] }}"
  run: "{{ cnt_docker_base_common['run'] }}"
  templates: "{{ cnt_docker_base_common['templates'] }}"
  access: "{{ cnt_docker_base_common['access'] }}"

# Define application package details
cnt_docker_profiles:
  snap: "{{ cnt_docker_profiles_common['snap'] }}"
  flatpak: "{{ cnt_docker_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      origin: "docker"
      packages:
        - name: "docker-ce"
        - name: "docker-ce-cli"
        - name: "containerd.io"

# Define custom package repositories
cnt_docker_repository_custom_yum:
  - name: "docker"
    description: "Docker CE Stable"
    url: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
cnt_docker_repository_custom_apt: []

# Set package repositories states
cnt_docker_repository_catalog_distro: {}
cnt_docker_repository_catalog_yum:
  docker: true
cnt_docker_repository_catalog_apt: {}
...
